riddler.settings:
  type: config_object
  mapping:
    riddles:
      type: sequence
      sequence:
        type: mapping
        mapping:
          question:
            type: label
            label: 'Question'
          response:
            type: label
            label: 'Response'