name: 'Config Actions Provider'
type: module
description: 'Apply config actions when applying configuration updates.'
# core: 8.x
dependencies:
  - 'config_actions:config_actions'
  - 'config_provider:config_provider (>=8.x-2.x)'
  - 'config_sync:config_sync'
# Information added by Drupal.org packaging script on 2019-02-15
version: '8.x-1.0-rc1'
core: '8.x'
project: 'config_actions_provider'
datestamp: 1550207287
