name: 'Config Merge'
type: module
description: 'Enables three-way merges of configuration items. This is useful for safely merging configuration updates while retaining any customizations.'
core: 8.x
core_version_requirement: ^8 || ^9
package: Config

# Information added by Drupal.org packaging script on 2020-05-29
version: '8.x-1.0-rc3'
project: 'config_merge'
datestamp: 1590770654
