path:
  - permissions
plugin: add
actions:
  'create campaign content':
    value: 'create campaign content'
  'delete own campaign content':
    value: 'delete own campaign content'
  'edit own campaign content':
    value: 'edit own campaign content'
