path:
  - permissions
plugin: add
actions:
  'create blog content':
    value: 'create blog content'
  'delete own blog content':
    value: 'delete own blog content'
  'edit own blog content':
    value: 'edit own blog content'
