path:
  - permissions
plugin: add
actions:
  'administer main menu items':
    value: 'administer main menu items'
  'use text format restricted_html':
    value: 'use text format restricted_html'
  'assign manager role':
    value: 'assign manager role'
  'assign editor role':
    value: 'assign editor role'
