path:
  - permissions
plugin: add
actions:
  'create page content':
    value: 'create page content'
  'delete own page content':
    value: 'delete own page content'
  'edit own page content':
    value: 'edit own page content'
