path:
  - permissions
plugin: add
actions:
  'create article content':
    value: 'create article content'
  'delete own article content':
    value: 'delete own article content'
  'edit own article content':
    value: 'edit own article content'
