# The content type we're changing settings for is landing_page.
actions:
  content_types:
    plugin: 'change'
    path: ['content_types', 'landing_page']
    actions:
      add_type:
        value: 'user'
  content_type_modes:
    plugin: 'add'
    path: ['content_type_modes', 'landing_page']
    actions:
      add_type_mode:
        value: 
          - 'full'