plugin: 'add'
actions:
  # Add config dependency.
  config_dependencies:
    path: ["dependencies", "config"]
    value: "field.field.node.page.field_storyline"
  # Add the entity form display settings.
  content:
    path: ["content"]
    value:
      field_storyline:
        type: entity_reference_paragraphs
        weight: 3
        settings:
          title: Paragraph
          title_plural: Paragraphs
          edit_mode: open
          add_mode: button
          form_display_mode: default
          default_paragraph_type: storyline_header
        third_party_settings: {  }
        region: content
