plugin: 'add'
actions:
  # Add config dependency.
  config_dependencies:
    path: ["dependencies", "config"]
    value: "field.field.node.page.field_storyline"
  # Add display suite settings.
  ds_settings:
    path: ["third_party_settings", "ds", "regions", "ds_content"]
    value: "field_storyline"
  # Add the field display settings.
  content:
    path: ["content"]
    value:
      field_storyline:
        type: entity_reference_revisions_entity_view
        weight: 1
        region: ds_content
        label: hidden
        settings:
          view_mode: default
          link: ''
        third_party_settings: {  }






