path:
  - permissions
plugin: add
actions:
  'create event content':
    value: 'create event content'
  'delete own event content':
    value: 'delete own event content'
  'edit own event content':
    value: 'edit own event content'
