path:
  - permissions
plugin: add
actions:
  'create event content':
    value: 'create event content'
  'delete event revisions':
    value: 'delete event revisions'
  'delete any event content':
    value: 'delete any event content'
  'edit any event content':
    value: 'edit any event content'
  'revert event revisions':
    value: 'revert event revisions'
  'view event revisions':
    value: 'view event revisions'
