path:
  - permissions
plugin: add
actions:
  'create action content':
    value: 'create action content'
  'delete own action content':
    value: 'delete own action content'
  'edit own action content':
    value: 'edit own action content'
